"""Synthetic v3 wire fixtures for parser/adapter tests only.

Copied from approved design examples, never an observed installation, actual
Registration/compiler output, published Registry root, or execution grant.
The full adapter/core/credential observations are intentionally retained.
"""
from copy import deepcopy

_WIRE = {'bindings': [{'account_binding_id': 'account-slot-a',
               'binding_id': 'binding-a',
               'binding_revision': 'r1',
               'renderer_id': 'credential-renderer',
               'renderer_implementation_sha256': 'd87aa8efe825c5342d7cb680b98b84920d2b59e2f401015894c12e4a1bc28588',
               'renderer_revision': 'r1',
               'renderer_unit_id': 'u.credentials',
               'resolver_id': 'secret-resolver',
               'resolver_implementation_sha256': 'd87aa8efe825c5342d7cb680b98b84920d2b59e2f401015894c12e4a1bc28588',
               'resolver_revision': 'r1',
               'resolver_unit_id': 'u.credentials',
               'service_id': 'service-main',
               'slot_id': 'credential-primary'}],
 'contract': {'assumptions': ['binding_identity',
                              'dependency_completeness',
                              'preparation_side_effect_contract'],
              'binding_slots': [{'account_binding_ids': ['account-slot-a'],
                                 'renderer': {'abi': 'rpnh/credential-renderer/v1',
                                              'id': 'credential-renderer',
                                              'implementation_unit_id': 'u.credentials',
                                              'revision': 'r1'},
                                 'resolver': {'abi': 'rpnh/opaque-secret-resolver/v1',
                                              'id': 'secret-resolver',
                                              'implementation_unit_id': 'u.credentials',
                                              'revision': 'r1'},
                                 'service_ids': ['service-main'],
                                 'slot_id': 'credential-primary'}],
              'contract_id': 'wire-contract',
              'coverage_basis': 'installer_declared_public_closure/v1',
              'execution_roots': {'adapter': ['u.adapter'],
                                  'before_dispatch': [],
                                  'configuration_sources': [],
                                  'executors': ['u.core'],
                                  'host_bindings': ['u.core'],
                                  'services': ['u.core'],
                                  'tools': []},
              'implementation_units': [{'asset_ids': ['u.adapter.asset'],
                                        'dependency_unit_ids': ['u.core'],
                                        'distribution': {'name': 'public-wire-fixture',
                                                         'version': '1.0'},
                                        'mode': 'installed_digest_identity',
                                        'runtime_abi': 'cpython-313',
                                        'unit_id': 'u.adapter'},
                                       {'asset_ids': ['u.core.asset'],
                                        'dependency_unit_ids': [],
                                        'distribution': {'name': 'public-wire-fixture',
                                                         'version': '1.0'},
                                        'mode': 'inline_public_bytes',
                                        'runtime_abi': 'cpython-313',
                                        'unit_id': 'u.core'},
                                       {'asset_ids': ['u.credentials.asset'],
                                        'dependency_unit_ids': ['u.core'],
                                        'distribution': {'name': 'public-wire-fixture',
                                                         'version': '1.0'},
                                        'mode': 'inline_public_bytes',
                                        'runtime_abi': 'cpython-313',
                                        'unit_id': 'u.credentials'}],
              'preparation_abi': 'rpnh/public_material_preparation/v1',
              'preparation_roots': {'catalog_factory': ['u.core'],
                                    'compiler': ['u.core'],
                                    'lowerer': ['u.core'],
                                    'profile_factory': ['u.core'],
                                    'registration_factory': ['u.core'],
                                    'serializer': ['u.core']},
              'profile_id': 'wire-profile',
              'public_slots': [{'body_schema_id': 'rpnh/public_execution_policy/v1',
                                'cardinality': 'one',
                                'role': 'execution_policy',
                                'selection_rule': {'kind': 'payload',
                                                   'payload_kind': 'agent_task',
                                                   'registration_key': None},
                                'slot_id': 'execution-default'}],
              'registrations': [{'implementation_unit_ids': ['u.core'],
                                 'key': 'component/wire_fixture/v1',
                                 'kind': 'component',
                                 'public_slot_ids': []},
                                {'implementation_unit_ids': ['u.core'],
                                 'key': 'executor/wire_fixture/v1',
                                 'kind': 'executor',
                                 'public_slot_ids': ['execution-default']}],
              'revision': 'r1',
              'schema_version': 'rpnh/installed_public_material_contract/v1',
              'supported_payloads': ['agent_task'],
              'supported_shape': {'agent_task_mode': 'single_stage_plugin_free',
                                  'local_process': False,
                                  'managed_plugins': False,
                                  'module_operations': [],
                                  'workflow': False}},
 'observations': {'u.adapter': {'assets': [{'asset_id': 'u.adapter.asset',
                                            'inline_node_id': None,
                                            'sha256': '40b9315fecff451afa6f83ea6b17680b67c5a9d00a46197f3463a6fffece6bc8',
                                            'size': 51}],
                                'contract_id': 'wire-contract',
                                'contract_revision': 'r1',
                                'distribution': {'name': 'public-wire-fixture', 'version': '1.0'},
                                'installation_id': 'installation-wire-example',
                                'installed_contract_sha256': '167e4cf408d74e0f6a86926066078c5d82256d3b495cf9260dd74ba117e86412',
                                'mode': 'installed_digest_identity',
                                'runtime': {'abi_tag': 'cpython-313',
                                            'implementation': 'cpython',
                                            'platform_tag': 'public-fixture-platform',
                                            'version': '3.13.0'},
                                'schema_version': 'rpnh/public_implementation_observation/v1',
                                'unit_id': 'u.adapter'},
                  'u.core': {'assets': [{'asset_id': 'u.core.asset',
                                         'inline_node_id': 'asset.u.core',
                                         'sha256': 'd50448a488adb9c67391163dd0c6734949da758f6a24e3d106d6b9b1105df270',
                                         'size': 48}],
                             'contract_id': 'wire-contract',
                             'contract_revision': 'r1',
                             'distribution': {'name': 'public-wire-fixture', 'version': '1.0'},
                             'installation_id': 'installation-wire-example',
                             'installed_contract_sha256': '167e4cf408d74e0f6a86926066078c5d82256d3b495cf9260dd74ba117e86412',
                             'mode': 'inline_public_bytes',
                             'runtime': {'abi_tag': 'cpython-313',
                                         'implementation': 'cpython',
                                         'platform_tag': 'public-fixture-platform',
                                         'version': '3.13.0'},
                             'schema_version': 'rpnh/public_implementation_observation/v1',
                             'unit_id': 'u.core'},
                  'u.credentials': {'assets': [{'asset_id': 'u.credentials.asset',
                                                'inline_node_id': 'asset.u.credentials',
                                                'sha256': '6ac9c89263d953a99386bfaf72e4517ecdcea465efa76743c1ed8cff55d053ab',
                                                'size': 55}],
                                    'contract_id': 'wire-contract',
                                    'contract_revision': 'r1',
                                    'distribution': {'name': 'public-wire-fixture',
                                                     'version': '1.0'},
                                    'installation_id': 'installation-wire-example',
                                    'installed_contract_sha256': '167e4cf408d74e0f6a86926066078c5d82256d3b495cf9260dd74ba117e86412',
                                    'mode': 'inline_public_bytes',
                                    'runtime': {'abi_tag': 'cpython-313',
                                                'implementation': 'cpython',
                                                'platform_tag': 'public-fixture-platform',
                                                'version': '3.13.0'},
                                    'schema_version': 'rpnh/public_implementation_observation/v1',
                                    'unit_id': 'u.credentials'}},
 'policy': {'adapter_kind': 'external_provider',
            'adapter_profile': {'config_schema_version': 'rpnh/public_external_provider_config/v1',
                                'recovery': {'max_probe_attempts': 2,
                                             'max_probe_success_formal_failure_cycles': 2,
                                             'probe_timeout_budget_seconds': 30,
                                             'strategy': 'bounded_same_route_health_probe/v1'},
                                'route_count': 1},
            'context_compaction_retained_tokens': 4096,
            'context_window_tokens': 32768,
            'default_reasoning_effort': 'high',
            'implementation_digest': 'f3fc6ab50d694817fe24b27b20c45f5b7ba4937d6c34e2332f2bdfa0943f5b0c',
            'implementation_unit_id': 'u.adapter',
            'max_output_tokens': 2048,
            'max_response_bytes': 1048576,
            'model_condition': 'selected-exact-model',
            'physical_profile_id': 'public-profile-a',
            'reasoning_effort': 'high',
            'route_provenance': [{'account_binding_id': 'account-slot-a',
                                  'backend': 'chat-completions',
                                  'credential_renderer_id': 'credential-renderer',
                                  'endpoint': 'https://api.example.invalid/v1/chat/completions',
                                  'outbound_model': 'selected-exact-model',
                                  'protocol': 'openai_chat_completions/v1',
                                  'provider': 'example-provider',
                                  'route_id': 'primary',
                                  'secret_binding_id': 'binding-a',
                                  'service_id': 'service-main',
                                  'transport': 'https'}],
            'runtime': {'context_pressure_trigger_ratio': 0.73,
                        'context_tool_output_byte_limit': 10000,
                        'main_history_message_limit': 20,
                        'max_parallel_nodes': 1,
                        'max_turns_per_node': 12,
                        'workspace': {'input_size_bytes': 16777216,
                                      'memory_bytes': 4294967296,
                                      'process_limit': 64,
                                      'source_size_bytes': 16777216,
                                      'timeout_seconds': 120}},
            'schema_version': 'rpnh/public_execution_policy/v1',
            'selection_id': 'selection-default',
            'supported_reasoning_efforts': ['high'],
            'timeout_seconds': 120}}

def public_wire():
    return deepcopy(_WIRE)
