#!/usr/bin/env python3
"""Read-only replay of reviewed publication inventory against local original sources."""
import argparse
import os
from pathlib import Path
import sys

sys.dont_write_bytecode = True
from publish_reviewed import (WORKSPACE, TASK, DESTINATION, PREFIXES, Refusal,
    checked, relative_path, read, digest, parse_json, load_gate, enumerate_selection,
    scan_private, transform, companion, public_readme, file_record, special_lists,
    check_final, stats, require)


def validate(destination=DESTINATION):
    destination = checked(destination)
    require(destination == DESTINATION, 'Validator only accepts the fixed evidence destination')
    manifest = parse_json(read(destination / 'publication-manifest.json'))
    gate_path = checked(WORKSPACE / relative_path(manifest['gate_source']), TASK)
    gate = load_gate(gate_path)
    selected, skipped, candidates, archives, controls, junit = enumerate_selection(gate_path, gate)
    require(manifest['destination'] == destination.relative_to(WORKSPACE).as_posix(), 'Destination mismatch')
    require(manifest['prefix_policy'] == [list(p) for p in PREFIXES], 'Prefix policy mismatch')
    for field, expected in [('selected_candidates', candidates), ('archive_metadata_only', archives),
                            ('excluded', skipped), ('final_control_json', controls),
                            ('final_accepted_junit', junit)]:
        require(manifest[field] == expected, f'Inventory {field} differs from current positive-list selection')
    records = manifest['files']
    require(len(records) == len(selected) and {r['target'] for r in records} == set(selected),
            'Original payload membership mismatch')
    expected_targets = set(selected) | {'README.md', 'publication-manifest.json'}
    expected_generated = {'README.md': ('public_readme', None)}
    payload = {}
    for record in records:
        target = record['target']
        entry = selected[target]
        original = read(entry['path'])
        require(not entry['expected_sha256'] or digest(original) == entry['expected_sha256'],
                f'Received lock mismatch: {record["source"]}')
        scan_private(original, record['source'])
        included, edits = transform(original, entry['path'].suffix, entry['frozen'])
        require(record == file_record(entry['path'], target, entry['category'], original,
                                     included, edits, entry['frozen']),
                f'Provenance/transformation mismatch: {target}')
        actual = read(destination / relative_path(target))
        require(actual == included, f'Replayed bytes mismatch: {target}')
        payload[target] = actual
        if record['nul_bytes'] or record['original_syntax'] == 'malformed':
            view = target + '.escaped-view.json'
            require(view not in expected_targets, f'Companion collision: {view}')
            expected_targets.add(view)
            expected_generated[view] = ('escaped_view', target)
    generated = manifest['generated']
    require(len(generated) == len(expected_generated) and
            {g['target'] for g in generated} == set(expected_generated), 'Generated membership mismatch')
    for record in generated:
        target = record['target']
        generator, raw_target = expected_generated[target]
        expected = public_readme() if generator == 'public_readme' else companion(payload[raw_target], raw_target)
        require(record['generator'] == generator, f'Unknown generator: {target}')
        require(record['category'] == ('public_index' if generator == 'public_readme' else 'escaped_companion'),
                f'Generated category mismatch: {target}')
        if raw_target:
            require(record['raw_payload'] == raw_target, f'Companion provenance mismatch: {target}')
        actual = read(destination / relative_path(target))
        require(actual == expected and digest(actual) == record['included_sha256'] and
                len(actual) == record['included_size'] and record['included_bytes'] == [0, len(actual)] and
                record['included_lines'] == [1, actual.count(b'\n') + 1], f'Generated bytes/hash/ranges mismatch: {target}')
        payload[target] = actual
    for name, expected in special_lists(records).items():
        require(manifest[name] == expected, f'Historical-original list mismatch: {name}')
    actual_targets = set()
    for directory, dirs, files in os.walk(destination, followlinks=False):
        for name in dirs + files:
            checked(Path(directory) / name, destination)
        for name in files:
            actual_targets.add((Path(directory) / name).relative_to(destination).as_posix())
    require(actual_targets == expected_targets, 'Payload contains missing/unlisted files')
    expected_selection = stats({'category': r['category'], 'size': r['original_size']} for r in records)
    require(manifest['selection'] == expected_selection, 'Selection counts/bytes mismatch')
    total = sum(len(read(destination / t)) for t in actual_targets)
    require(0 < manifest['budget_bytes'] and total <= manifest['budget_bytes'], 'Payload budget exceeded')
    check_final(payload, controls, junit)
    print(f'VALIDATED: {len(actual_targets)} evidence/control files, {total} bytes; historical malformed originals explicitly preserved.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--run', action='store_true', help='Explicitly perform read-only local validation')
    args = parser.parse_args()
    require(args.run, 'Inert: explicit --run required')
    validate()


if __name__ == '__main__':
    try:
        main()
    except (Refusal, OSError, ValueError, KeyError, TypeError) as exc:
        print(str(exc) if isinstance(exc, Refusal) else f'Aborted ({type(exc).__name__}); inspect inputs privately', file=sys.stderr)
        sys.exit(1)
